version: '3'

services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  nginx:
    image: nginx
    volumes:
      - ./nginx.grafana.conf:/etc/nginx/conf.d/nginx.grafana.conf
    ports:
      - 8000:80
  
  nginx-node-exporter:
    image: nginx/nginx-prometheus-exporter:1.0.0
    ports:
      - 9113:9113
    command: --nginx.scrape-uri=http://nginx:81/nginx_status
